### ISSUE TITLE
Project Structure Confusing

### ISSUE THREAD

**Issue by edisonzsq** [Kern000/projectTwoFrontEnd-ReactNative#1]
You can research online how to properly structure a react native project, such as https://medium.com/the-andela-way/how-to-structure-a-react-native-app-for-scale-a29194cd33fc

For example, you have a `pageComponent` folder. Is it a page or a component? Page usually refer to a certain screen. Components are what aggregate together and forms a certain screen. Components are also reusable.

**Comment by Kern000** [comment]
Thanks, this is helpful. They are pages, so I will be renaming pages as pages, and components as components

**Comment by Kern000** [comment]
created better structure, organizing components in components folder and pages in pages folder.
